spring:
  thymeleaf:
    prefix: file:./front/templates/
    cache: true
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      idle-timeout: 12000
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    open-in-view: false
logging:
  level:
    root: warn